### ISSUE TITLE
Program termination remarks are uncreative

### ISSUE THREAD

**Issue by op2rules** [op2rules/wim-hof-breathing-helper#13]
It's great to remind the user that Wim would be proud, but what if we add quotes from Wim and people who have used the application?

There are plenty of Wim Hot quotes online, as well as some famous ones we've already seen:

"I feel the best I am going to feel all day when I do Wim Hof. I've never regretted doing it" - Steven Massicotte
"I see open eye visuals when I do the breath hold" - Sebastian Jurga
"It's so fucking good man" - Aaron Massicotte

**Comment by op2rules** [comment]
Implemented in https://github.com/op2rules/wim-hof-breathing-helper/pull/14

**Comment by ejurga** [comment]
Great idea. Reviewed, and merged.
